### ISSUE TITLE
Minor errors in the CSS

### ISSUE THREAD

**Issue by socketpal25** [clifford269/FrutigerFX#3]
Hello... this is the current theme i use for Firefox 115 ESR and as far as i tested it there were no major problems! There are some nitpicks from my part though. Tested on Windows 7

1. The buttons when you configure the bookmarks menu are not adjusted correctly:
![error 1](https://github.com/user-attachments/assets/34c8197b-8d03-461a-95c2-68a866ea4d51)

2. In the private search interface, the typed text on the search bar is wrongfully sized, as it can be seen with the black line in the picture.
![error 2](https://github.com/user-attachments/assets/3c4d1614-8a6e-4e61-80ec-62eb44912531)

I would like to know if this does happen because of language incompatibilities as I'm using Spanish as the main language of my browser.

**Comment by clifford269** [comment]
An update is ready to be pushed, soon. It's an overhaul which fixes the first error you described. As for the second, the search bar is just an eye-candy. It's made defunct by Mozilla. The moment you'll type in, it will hop back to the top!
