### ISSUE TITLE
"Failed to load configuration file"

### ISSUE THREAD

**Issue by winbamstudios** [clifford269/FrutigerFX#7]
I followed all of the steps in the tutorial (Win7 Ultimate btw), yet it gives me an error that it "failed to load the config file." Maybe the issue is that FrutigerFX links British English 115.15.0esr, and I'm using US English 115.16.0esr. Not sure.

**Comment by SucculentJohn** [comment]
you need to follow the   instructions did you poute yo thangs correctly and follw the rules 

for inquiries message me on google+

**Comment by duckduckgroose** [comment]
Did you solve this? I also get this message when I get onto firefox
